include $(USER_DEPTH)/make/makeinclude/mk_pre.mak

USER_BIN = ipstacktcpclient

USER_SRCS_CPP = ipstacktcpclient.cpp

USER_LINK_DLLS =

USER_INCLDIRS =
USER_DEFFLAGS =
USER_LINK_LIBS = 
USER_LINK_FLAGS= -L$(USER_DEPTH)/target
USER_OBJ_DIR=$(TARGET_PATH)/src/ipstacktcpclient
include $(USER_DEPTH)/make/makeinclude/mk_post.mak
